test:
  adapter: postgresql
  database: accounts_dummy_test
  host:     <%= ENV.fetch("PGHOST",     "localhost") %>
  port:     <%= ENV.fetch("PGPORT",     "5432") %>
  username: <%= ENV.fetch("PGUSER",     ENV["USER"]) %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  pool: 5
  encoding: unicode
